config/routes.rb
Rails.application.routes.draw do
  mount Lockup::Engine, at: '/lockup'
  root 'welcome#index'
  resources :affiliates
  resources :offers
  resources :tiers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/affiliate.rb
class Affiliate < ApplicationRecord
  validates :name, presence: true
  validates :affid, presence: true
  belongs_to :tier, optional:true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/offer.rb
class Offer < ApplicationRecord
  validates :title, presence: true
  validates :link_to_image, presence: true
  validates :lp_offer_name, presence: true
  belongs_to :tier, optional:true
end

app/models/tier.rb
class Tier < ApplicationRecord
  validates :title, presence: true 
  validates :vertical_name, presence: true
  has_many :tier_offers
  has_many :offers, through: :tier_offers
  has_many :tier_affiliates
  has_many :affiliates, through: :tier_affiliates
end

app/models/tier_affiliate.rb
class TierAffiliate < ApplicationRecord
  belongs_to :tier
  belongs_to :affiliate
end

app/models/tier_offer.rb
class TierOffer < ApplicationRecord
  belongs_to :tier
  belongs_to :offer
end

app/controllers/affiliates_controller.rb
class AffiliatesController < ApplicationController
  before_action :set_affiliate, only: [:show, :edit, :update, :destroy]

  # GET /affiliates
  def index
    @affiliates = Affiliate.all
  end

  # GET /affiliates/1
  def show
  end

  # GET /affiliates/new
  def new
    @affiliate = Affiliate.new
  end

  # GET /affiliates/1/edit
  def edit
  end

  # POST /affiliates
  def create
    @affiliate = Affiliate.new(affiliate_params)

    if @affiliate.save
      redirect_to @affiliate, notice: 'Affiliate was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /affiliates/1
  def update
    if @affiliate.update(affiliate_params)
      redirect_to @affiliate, notice: 'Affiliate was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /affiliates/1
  def destroy
    @affiliate.destroy
    redirect_to affiliates_url, notice: 'Affiliate was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_affiliate
      @affiliate = Affiliate.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def affiliate_params
      params.require(:affiliate).permit(:name, :affid)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_action :set_offer, only: [:show, :edit, :update, :destroy]

  # GET /offers
  def index
    @offers = Offer.all
  end

  # GET /offers/1
  def show
  end

  # GET /offers/new
  def new
    @offer = Offer.new
  end

  # GET /offers/1/edit
  def edit
  end

  # POST /offers
  def create
    @offer = Offer.new(offer_params)

    if @offer.save
      redirect_to @offer, notice: 'Offer was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /offers/1
  def update
    if @offer.update(offer_params)
      redirect_to @offer, notice: 'Offer was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /offers/1
  def destroy
    @offer.destroy
    redirect_to offers_url, notice: 'Offer was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_offer
      @offer = Offer.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def offer_params
      params.require(:offer).permit(:title, :link_to_image, :is_capped, :EPC, :lp_offer_name, :rank)
    end
end

app/controllers/tiers_controller.rb
class TiersController < ApplicationController
  before_action :set_tier, only: [:show, :edit, :update, :destroy]

  # GET /tiers
  def index
    @tiers = Tier.all
  end

  # GET /tiers/1
  def show
  end

  # GET /tiers/new
  def new
    @tier = Tier.new
  end

  # GET /tiers/1/edit
  def edit
  end

  # POST /tiers
  def create
    @tier = Tier.new(tier_params)

    if @tier.save
      redirect_to @tier, notice: 'Tier was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /tiers/1
  def update
    if @tier.update(tier_params)
      redirect_to @tier, notice: 'Tier was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /tiers/1
  def destroy
    @tier.destroy
    redirect_to tiers_url, notice: 'Tier was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tier
      @tier = Tier.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def tier_params
      params.require(:tier).permit(:title, :vertical_name, tier_ids:[])
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/affiliates_helper.rb
module AffiliatesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/helpers/tiers_helper.rb
module TiersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/affiliates/_form.html.erb
<%= form_for(affiliate) do |f| %>
  <% if affiliate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(affiliate.errors.count, "error") %> prohibited this affiliate from being saved:</h2>

      <ul>
      <% affiliate.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :affid %>
    <%= f.text_field :affid %>
  </div>

  <h3>Choose The Tier(s) This Affiliate Belongs To</h3>
  <div class=“field”>
    <%= f.collection_check_boxes :tier, Tier.all, :id, :title %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/affiliates/edit.html.erb
<h1>Editing Affiliate</h1>

<%= render 'form', affiliate: @affiliate %>

<%= link_to 'Show', @affiliate %> |
<%= link_to 'Back', affiliates_path %>

app/views/affiliates/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Affiliates</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Affid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @affiliates.each do |affiliate| %>
      <tr>
        <td><%= affiliate.name %></td>
        <td><%= affiliate.affid %></td>
        <td><%= link_to 'Show', affiliate %></td>
        <td><%= link_to 'Edit', edit_affiliate_path(affiliate) %></td>
        <td><%= link_to 'Destroy', affiliate, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Affiliate', new_affiliate_path %>

app/views/affiliates/new.html.erb
<h1>New Affiliate</h1>

<%= render 'form', affiliate: @affiliate %>

<%= link_to 'Back', affiliates_path %>

app/views/affiliates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @affiliate.name %>
</p>

<p>
  <strong>Affid:</strong>
  <%= @affiliate.affid %>
</p>

<%= link_to 'Edit', edit_affiliate_path(@affiliate) %> |
<%= link_to 'Back', affiliates_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Adx</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <nav id="navbar">
    <ul>
      <li><a href="/tiers">Tiers</a></li>
      <li><a href="/offers">Offers</a></li>
      <li><a href="/affiliates">Affiliates</a></li>
    </ul>
  </nav>

  <body>
    <%= yield %>
  </body>
</html>

app/views/offers/_form.html.erb
<%= form_for(offer) do |f| %>
  <% if offer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(offer.errors.count, "error") %> prohibited this offer from being saved:</h2>

      <ul>
      <% offer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :link_to_image %>
    <%= f.text_field :link_to_image %>
  </div>

  <div class="field">
    <%= f.label :is_capped %>
    <%= f.check_box :is_capped %>
  </div>

  <div class="field">
    <%= f.label :EPC %>
    <%= f.text_field :EPC %>
  </div>

  <div class="field">
    <%= f.label :lp_offer_name %>
    <%= f.text_field :lp_offer_name %>
  </div>

  <div class="field">
    <%= f.label :rank %>
    <%= f.number_field :rank %>
  </div>

  <div class=“field”>
    <%= f.label :tier %>
    <%= f.collection_check_boxes :tier, Tier.all, :id, :title %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/offers/edit.html.erb
<h1>Editing Offer</h1>

<%= render 'form', offer: @offer %>

<%= link_to 'Show', @offer %> |
<%= link_to 'Back', offers_path %>

app/views/offers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Offers</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Link to image</th>
      <th>Is capped</th>
      <th>Epc</th>
      <th>Lp offer name</th>
      <th>Rank</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @offers.each do |offer| %>
      <tr>
        <td><%= offer.title %></td>
        <td><%= offer.link_to_image %></td>
        <td><%= offer.is_capped %></td>
        <td><%= offer.EPC %></td>
        <td><%= offer.lp_offer_name %></td>
        <td><%= offer.rank %></td>
        <td><%= link_to 'Show', offer %></td>
        <td><%= link_to 'Edit', edit_offer_path(offer) %></td>
        <td><%= link_to 'Destroy', offer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Offer', new_offer_path %>

app/views/offers/new.html.erb
<h1>New Offer</h1>

<%= render 'form', offer: @offer %>

<%= link_to 'Back', offers_path %>

app/views/offers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @offer.title %>
</p>

<p>
  <strong>Link to image:</strong>
  <%= @offer.link_to_image %>
</p>

<p>
  <strong>Is capped:</strong>
  <%= @offer.is_capped %>
</p>

<p>
  <strong>Epc:</strong>
  <%= @offer.EPC %>
</p>

<p>
  <strong>Lp offer name:</strong>
  <%= @offer.lp_offer_name %>
</p>

<p>
  <strong>Rank:</strong>
  <%= @offer.rank %>
</p>

<%= link_to 'Edit', edit_offer_path(@offer) %> |
<%= link_to 'Back', offers_path %>

app/views/tiers/_form.html.erb
<%= form_for(tier) do |f| %>
  <% if tier.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tier.errors.count, "error") %> prohibited this tier from being saved:</h2>

      <ul>
      <% tier.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :vertical_name %>
    <%= f.text_field :vertical_name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tiers/edit.html.erb
<h1>Editing Tier</h1>

<%= render 'form', tier: @tier %>

<%= link_to 'Show', @tier %> |
<%= link_to 'Back', tiers_path %>

app/views/tiers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tiers</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Vertical name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tiers.each do |tier| %>
      <tr>
        <td><%= tier.title %></td>
        <td><%= tier.vertical_name %></td>
        <td><%= link_to 'Show', tier %></td>
        <td><%= link_to 'Edit', edit_tier_path(tier) %></td>
        <td><%= link_to 'Destroy', tier, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tier', new_tier_path %>

app/views/tiers/new.html.erb
<h1>New Tier</h1>

<%= render 'form', tier: @tier %>

<%= link_to 'Back', tiers_path %>

app/views/tiers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @tier.title %>
</p>

<p>
  <strong>Vertical name:</strong>
  <%= @tier.vertical_name %>
</p>

<%= link_to 'Edit', edit_tier_path(@tier) %> |
<%= link_to 'Back', tiers_path %>

app/views/welcome/index.html.erb
<h2>What are you doing with your life?</h2>
<p>
  The time is now: <%= Time.now %>
</p>